### ISSUE TITLE
f-join not working as expected

### ISSUE THREAD

**Issue by jcs090218** [rejeep/f.el#100]
I am trying to join two path using `f-join` function.

```el
(message "%s" (f-join "C:/Program Files (x86)/Microsoft Visual Studio/" "/Community/VC/Tools/MSVC/"))
```

Output

```
c:/Community/VC/Tools/MSVC/
```

Expected Output

```
C:/Program Files (x86)/Microsoft Visual Studio/Community/VC/Tools/MSVC/
```

Any idea? 😕

**Comment by Phundrak** [comment]
It seems `f-relative?` does not recognize paths beginning with a drive name as absolute paths on Windows, which might be the reason for this bug.
```lisp
(f-relative? "c:/") ;; nil
(f-relative? "C:/") ;; nil
(f-relative? "d:/") ;; nil
(f-relative? "D:/") ;; nil
```

**Comment by Phundrak** [comment]
It seems the bug comes from somewhere in `expand-file-name`, as seen with the following example:
```lisp
(expand-file-name "/Community/VC/Tools/MSVC/"
                  "C:/Program Files (x86)/Microsoft Visual Studio/")
;; => "c:/Community/VC/Tools/MSVC/"
```
This might be an Emacs bug. Tested in Emacs 28.1. However, the following works:
```lisp
(f-join "C:/Program Files (x86)/Microsoft Visual Studio/"
        "Community/VC/Tools/MSVC/")
;; => "c:/Program Files (x86)/Microsoft Visual Studio/Community/VC/Tools/MSVC/"
```
The leading `/` might be what causes the bug.

**Comment by Phundrak** [comment]
As the current behavior of `f-join` follows the behavior of `expand-file-name`, and as changing it might lead to breaking changes, I decided to tag this issue with *wontfix*.

This is also the behavior of several other programing languages.

### Python
```python
from os.path import join
print(join("C:/path/to", "/a"))
```

    /a

### C++
```C++
#include <filesystem>
namespace fs = std::filesystem;
int main() {
    fs::path p1 = "C:/path/to";
    p1 /= "/a";
    std::cout << p1 << '\n';
}
```

    /a
