### ISSUE TITLE
[Feature request] `f-newer-p` and `f-older-p`

### ISSUE THREAD

**Issue by rileyrg** [rejeep/f.el#102]
Any chance of a "newer" function? ie (if (f-newer fileA fileB) ) ... fileA is newer than fileB...

**Comment by rileyrg** [comment]
silly me. there is one.

**Comment by Phundrak** [comment]
I think this would be a nice addition to `f`. `f-newer-p` could also be accompanied by `f-older-p`, though the person implementing it should be wary not to define one as being the opposite of the other, two files could be created at the same time.
