### ISSUE TITLE
[Bug]: Symbol's function definition is void: define-short-documentation-group

### ISSUE THREAD

**Issue by ybgwon** [rejeep/f.el#120]
### Expected behavior

Normal loading

### Actual behavior

Library loading fail.
Emacs says below error.
"Symbol's function definition is void: define-short-documentation-group"

### f.el version

0.20.0

### Emacs version

something else (please specify)

### Relevant code or log output

```emacs-lisp
emacs-version is a variable defined in ‘C source code’.
Its value is "29.0.50"

(when (version<= "28.1" emacs-version)
   (require 'f-shortdoc))

I think it's a problem with the above code.
```

**Comment by daanturo** [comment]
Your Emacs version is outdated, it's now 29.0.60, please update
@Phundrak this just a issue of using an outdated development version

**Comment by Phundrak** [comment]
Alright, I could not verify since I’m on Emacs 30.0.50, I initially
reverted the commit out of precaution. I added back the commit

**Comment by ybgwon** [comment]
I'm not using newest distro. I'm using ubuntu bionic based distro.

I use below repo for emacs-snapshot.
deb http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu bionic main

$ apt update && apt install emacs-snapshot
...
emacs-snapshot is already the newest version (20220430:105493-4ea8ab77e2~ubuntu18.04.1).

**Comment by Phundrak** [comment]
It simply means your repository’s version is outdated, Emacs snapshot got bumped to version 30.0.50 by the end of November. And based on the version you shared, it hasn’t been updated since April 30th, 2022. I would advise you not to use this package and either compile Emacs yourself if you want its development version or fall back to a stable version.

**Comment by ybgwon** [comment]
Yes, you are right !
Thank you.
