### ISSUE TITLE
[Bug]: Doesn't load `shortdoc` with Emacs 29, causing `(void-function define-short-documentation-group)` on startup with doom-emacs

### ISSUE THREAD

**Issue by Ruin0x11** [rejeep/f.el#121]
### Expected behavior

The library should load correctly.

### Actual behavior

When I start doom-emacs I get this error:

```
Error (doom-after-init-hook): Error running hook "doom-modeline-mode" because: (void-function define-short-documentation-group)
```

I think it's because the `shortdoc` library isn't required automatically with my Emacs. If I `(load-library 'shortdoc)` by hand then `define-short-documentation-group` is defined correctly.

### f.el version

0.20.0

### Emacs version

something else (please specify)

### Relevant code or log output

```emacs-lisp
(when (version<= "28.1" emacs-version)
  (when (< emacs-major-version 29)
    (require 'shortdoc))
```

```
GNU Emacs 29.0.50 (build 1, x86_64-w64-mingw32) of 2022-04-02
```

**Comment by Phundrak** [comment]
Duplicate of #120. Your Emacs version is outdated, the latest version for Emacs 29 is 29.0.60, please update it.
