### ISSUE TITLE
[Bug]: f-descendant and others give wrong results on dirs that share a prefix.

### ISSUE THREAD

**Issue by ilitzroth** [rejeep/f.el#126]
### Expected behavior

(f-descendant-of-p "libacbusutils/modelutils.hpp"  "libacbus") -> nil

### Actual behavior

(f-descendant-of-p "libacbusutils/modelutils.hpp"  "libacbus")  -> t

### f.el version

master

### Emacs version

28.1

**Comment by Phundrak** [comment]
Thanks for the bug report! It is indeed an error, I’ll look into it.

**Comment by Phundrak** [comment]
Can you try the branch fix/issue-126 and see if it resolves this issue on your side?
