### ISSUE TITLE
v0.18.0 tag

### ISSUE THREAD

**Issue by spwhitton** [rejeep/f.el#52]
Hello,

Version 0.18.0 has not yet been released, but the f.el repository has a v0.18.0 tag.  This is confusing Debian tooling which thinks that a new upstream version is available.  I would really appreciate it if this false tag could be removed:

    git tag -d v0.18.0
    git push origin :refs/tags/v0.18.0

Thanks.

Sean

**Comment by rejeep** [comment]
Thanks for reporting, removed! :+1:
