### ISSUE TITLE
where is version 0.18

### ISSUE THREAD

**Issue by dischoen** [rejeep/f.el#53]
hi,

i come here via trying to install https://github.com/mrkkrp/ebal,
which currently refers to 0.18.0 of your package.

i found one commit, https://github.com/rejeep/f.el/commit/7003428ead6d80e81ff14c3614239efdbce7391b, but the version of f.el within the file is 0.17.2

**Comment by rejeep** [comment]
That's a really good question... :smile: 

I forgot to update the version in `f.el`. Release `v0.18.1` now, thanks for reporting.
