### ISSUE TITLE
Version 1.18.1 or 0.18.1?

### ISSUE THREAD

**Issue by spwhitton** [rejeep/f.el#54]
The new release is tagged 1.18.1, but in f.el the release is given as 0.18.1.  Which is correct?  Since the previous release was 0.17.3 I assume that the new one is 0.18.1 and the tag is incorrect, but please confirm.  Thanks!

**Comment by rejeep** [comment]
Thanks for reporting this, I removed the `v1.18.1` tag. `v0.18.1` is the correct one!
