### ISSUE TITLE
No changes in v0.18.1?

### ISSUE THREAD

**Issue by spwhitton** [rejeep/f.el#55]
Given

    artemis ~/src/f-el % git diff v0.17.3..v0.18.1
    diff --git a/f.el b/f.el
    index 8d3223e..f2e077c 100644
    --- a/f.el
    +++ b/f.el
    @@ -4,7 +4,7 @@
     
     ;; Author: Johan Andersson <johan.rejeep@gmail.com>
     ;; Maintainer: Johan Andersson <johan.rejeep@gmail.com>
    -;; Version: 0.17.3
    +;; Version: 0.18.1
     ;; Keywords: files, directories
     ;; URL: http://github.com/rejeep/f.el
     ;; Package-Requires: ((s "1.7.0") (dash "2.2.0"))

did you perhaps forget to merge in the development branch before tagging the new release?  Thanks.

**Comment by rejeep** [comment]
I messed up the tagging a bit I'm afraid... :confused: Will try to get this right in the future.

**Comment by spwhitton** [comment]
So are you saying that 0.18.* has not yet been released?  Perhaps you could delete the tag in that case.

**Comment by rejeep** [comment]
Sorry for being lazy replying to this.

No, the problem is that I release v0.18, then accidentally v0.17, so I released a v0.18 dummy on top of that.
