### ISSUE TITLE
Posix stat metadata

### ISSUE THREAD

**Issue by priyadarshan** [rejeep/f.el#57]
Would it be possible to add something like `f-stat`, which would return [Posix](https://en.wikipedia.org/wiki/Inode#POSIX_inode_description) `stat` metadata about a given path?

Right now one would need to have a system call to fecth that metadata.

```
(f-stat "file.txt")
;; device  16777222
;; inode   4080486
;; mode    33188
;; nlink   1
;; uid     501
;; gid     20
;; rdev    0
;; size    1500520
;; atime   1451758319
;; mtime   1423242348
;; ctime   1451831422
;; blksize 4096
;; blocks  2936
;; link nil
```
I find `f.el` extremely useful. Thank you so much.

**Comment by rejeep** [comment]
Give it a shot, perhaps possible using https://github.com/rejeep/f.el/blob/master/f.el#L386?

**Comment by priyadarshan** [comment]
Nice, why did I not think of that! Elisp has extended attributes introspection too (https://www.gnu.org/software/emacs/manual/html_node/elisp/Extended-Attributes.html). Thank you. I shall give it a try.

**Comment by priyadarshan** [comment]
Thank you for the pointer, it works as intended.

It would still be quite nice to be able to access such information through `f.el` API, i.e. perhaps by adding some syntactic sugar to allow easier extraction of the Posix metadata.

Right now one needs to do a bit of cavorting in order to do that.

**Comment by rejeep** [comment]
Why don't you use the raw functions for a while and get back if you figure out an API that make sense. Otherwise I think it will be hard to come up with a good API.

**Comment by priyadarshan** [comment]
Just a quick addition, for future reference: Emacs 26.0.50 is offering more file details. From [NEWS](https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS) file:

```
+++
** Several accessors for the value returned by 'file-attributes'
have been added.  They are: 'file-attribute-type',
'file-attribute-link-number', 'file-attribute-user-id',
'file-attribute-group-id', 'file-attribute-access-time',
'file-attribute-modification-time',
'file-attribute-status-change-time', 'file-attribute-size',
'file-attribute-modes', 'file-attribute-inode-number',
'file-attribute-device-number' and 'file-attribute-collect'.
```
