### ISSUE TITLE
f-join is trying to open a tramp connection when it shouldn't

### ISSUE THREAD

**Issue by tmalsburg** [rejeep/f.el#58]
``` elisp
(f-join (f-root) "C:\\Users\\61169.html")
```

Surprisingly, this gives me the following when executed on linux:

```
ssh: Could not resolve hostname c: Name or service not known
```

and

```
Tramp: Waiting for prompts from remote shell...failed
Tramp: Opening connection for C using scp...failed
tramp-file-name-handler: Tramp failed to connect.  If this happens repeatedly, try
    ‘M-x tramp-cleanup-this-connection’
```

I understand that I'm feeding `f-join` with garbage but I think it should nevertheless not attempt to open connections.

**Comment by rejeep** [comment]
Thanks for reporting. Closing this in favour of https://github.com/rejeep/f.el/pull/59. Can you verify that this works please!?
