### ISSUE TITLE
f-uniquify-alist performance issue on files vs directories

### ISSUE THREAD

**Issue by FrancisMurillo** [rejeep/f.el#62]
Great library guys, real help.

So I've been using `f-uniquify-alist` along with `projectile` which is cool. I just noticed in a big project where there are 642 files and 140 directories, said function hangs when I run it with `projectile-current-project-dirs` and weirdly it doesn't hang when it is run with `projectile-current-project-files`. This is sort of weird when there are more files than there are directories and yet it chokes.

After some investigation, given a minimal test path list of `(list "a/b/c/d/" "a/B/c/d/")`; this creates an infinite loop with `(s-chop-prefix "d" "a/b/c/d")` instead of the correct `(s-chop-prefix "d/" "a/b/c/d")`.

**Comment by rejeep** [comment]
Closing via https://github.com/rejeep/f.el/pull/63
