### ISSUE TITLE
f-entries can't handle unreadable directories

### ISSUE THREAD

**Issue by ambihelical** [rejeep/f.el#78]
If the directory tree being traversed by f-entries has any unreadable directories, 
f-entries still tries to recurse into it and throws an error.  Here ~/.cache/dconf is
not readable by the emacs process, and f-entries returns no results:

```
ELISP> (f-entries "/home/work/.cache/" nil t)
*** Eval error ***  Opening directory: Permission denied, /home/work/.cache/dconf
```

The expected result should be that unreadable directories are in the results, but no recursion is performed on them.

**Comment by Phundrak** [comment]
Fixed with the merge of #79.
